"""Public API for `animus-plugin-sdk`.

Re-exports the small set of entrypoints plugin authors should reach for.
The internal wire and handshake helpers are also exported for advanced
and test use, but are documented as low-level.
"""

from .handshake import (
    PluginIdentity,
    build_initialize_result,
    build_manifest,
    validate_initialize_params,
)
from .plugin import PluginHandle, PluginSpec, define_plugin
from .roles import (
    CallContext,
    HealthReport,
    LogStorageBackend,
    Provider,
    ProviderRunParams,
    ProviderRunResult,
    SubjectBackend,
    SubjectCallContext,
    TransportBackend,
    TriggerBackend,
    TriggerEvent,
)
from .types import (
    PROTOCOL_VERSION,
    EnvRequirement,
    ErrorCode,
    HealthCheckResult,
    HealthStatus,
    HostCapabilities,
    HostInfo,
    InitializeParams,
    InitializeResult,
    McpTool,
    PluginCapabilities,
    PluginInfo,
    PluginKind,
    PluginKindString,
    PluginManifest,
    RpcError,
    RpcId,
    RpcNotification,
    RpcRequest,
    RpcResponse,
    Subject,
    SubjectCreateRequest,
    SubjectListParams,
    SubjectListResult,
    SubjectPatch,
    SubjectStatus,
)
from .wire import (
    Wire,
    create_wire,
    encode_frame,
    error_response,
    ok_response,
    parse_frame,
)

__version__ = "0.1.0"

__all__ = [
    "PROTOCOL_VERSION",
    "CallContext",
    "EnvRequirement",
    "ErrorCode",
    "HealthCheckResult",
    "HealthReport",
    "HealthStatus",
    "HostCapabilities",
    "HostInfo",
    "InitializeParams",
    "InitializeResult",
    "LogStorageBackend",
    "McpTool",
    "PluginCapabilities",
    "PluginHandle",
    "PluginIdentity",
    "PluginInfo",
    "PluginKind",
    "PluginKindString",
    "PluginManifest",
    "PluginSpec",
    "Provider",
    "ProviderRunParams",
    "ProviderRunResult",
    "RpcError",
    "RpcId",
    "RpcNotification",
    "RpcRequest",
    "RpcResponse",
    "Subject",
    "SubjectBackend",
    "SubjectCallContext",
    "SubjectCreateRequest",
    "SubjectListParams",
    "SubjectListResult",
    "SubjectPatch",
    "SubjectStatus",
    "TransportBackend",
    "TriggerBackend",
    "TriggerEvent",
    "Wire",
    "__version__",
    "build_initialize_result",
    "build_manifest",
    "create_wire",
    "define_plugin",
    "encode_frame",
    "error_response",
    "ok_response",
    "parse_frame",
    "validate_initialize_params",
]
